### ISSUE TITLE
D10 - En tant que marchand authentifié, je dois pouvoir voir un registre des opérations faites par mon site avec un libelé explicatif

### ISSUE THREAD

**Issue by AlexisMichaudETS** [gti525/h18-passerelle#12]

**Comment by Koyyvo** [comment]
Ne pas oublier de fetch le montant de la transaction

**Comment by daren511** [comment]
Le libelé explicatif (https://docs.google.com/spreadsheets/d/1BatYGkWW5BFnZQ6_VDVN8gOuE-H69t_ipEghhvwtLqk/edit#gid=424296027&range=C11)
